//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.JAccessManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webjedmics.net/jedmicsws/services/AccessManager", ConfigurationName="JAccessManager.AccessManagerObj")]
    public interface AccessManagerObj {
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect2();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect2Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect3();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect3Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect4();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect4Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect5();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connect5Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void disconnect();
        
        [System.ServiceModel.OperationContractAttribute()]
        void disconnectAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void hasPermission();
        
        [System.ServiceModel.OperationContractAttribute()]
        void hasPermissionAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndMapSingleLoginNew();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndMapSingleLoginNewAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSave();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSave1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSave1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNewAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew2();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew2Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew3();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew3Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew4();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew4Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew5();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew5Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew6();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew6Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew7();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew7Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew8();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew8Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew9();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectNew9Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveNew();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveNewAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveNew1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveNew1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveNew2();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectAndSaveNew2Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void changePassword();
        
        [System.ServiceModel.OperationContractAttribute()]
        void changePasswordAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void changePassword1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void changePassword1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void changePassword2();
        
        [System.ServiceModel.OperationContractAttribute()]
        void changePassword2Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void isAccountActive();
        
        [System.ServiceModel.OperationContractAttribute()]
        void isAccountActiveAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void isAccountActive1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void isAccountActive1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getAccessRights();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getAccessRightsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void generatePassword();
        
        [System.ServiceModel.OperationContractAttribute()]
        void generatePasswordAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void isSessionValid();
        
        [System.ServiceModel.OperationContractAttribute()]
        void isSessionValidAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void auditGovtWarning();
        
        [System.ServiceModel.OperationContractAttribute()]
        void auditGovtWarningAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void headerLogin();
        
        [System.ServiceModel.OperationContractAttribute()]
        void headerLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectPkiAndUserId();
        
        [System.ServiceModel.OperationContractAttribute()]
        void connectPkiAndUserIdAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void proxyLoginAndUserID();
        
        [System.ServiceModel.OperationContractAttribute()]
        void proxyLoginAndUserIDAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void unMapCert();
        
        [System.ServiceModel.OperationContractAttribute()]
        void unMapCertAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void unMapProxyId();
        
        [System.ServiceModel.OperationContractAttribute()]
        void unMapProxyIdAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getUserProfile();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getUserProfileAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccessManagerObjChannel : ConsoleApplication1.JAccessManager.AccessManagerObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessManagerObjClient : System.ServiceModel.ClientBase<ConsoleApplication1.JAccessManager.AccessManagerObj>, ConsoleApplication1.JAccessManager.AccessManagerObj {
        
        public AccessManagerObjClient() {
        }
        
        public AccessManagerObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessManagerObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessManagerObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessManagerObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void connect() {
            base.Channel.connect();
        }
        
        public void connectAsync() {
            base.Channel.connectAsync();
        }
        
        public void connect1() {
            base.Channel.connect1();
        }
        
        public void connect1Async() {
            base.Channel.connect1Async();
        }
        
        public void connect2() {
            base.Channel.connect2();
        }
        
        public void connect2Async() {
            base.Channel.connect2Async();
        }
        
        public void connect3() {
            base.Channel.connect3();
        }
        
        public void connect3Async() {
            base.Channel.connect3Async();
        }
        
        public void connect4() {
            base.Channel.connect4();
        }
        
        public void connect4Async() {
            base.Channel.connect4Async();
        }
        
        public void connect5() {
            base.Channel.connect5();
        }
        
        public void connect5Async() {
            base.Channel.connect5Async();
        }
        
        public void disconnect() {
            base.Channel.disconnect();
        }
        
        public void disconnectAsync() {
            base.Channel.disconnectAsync();
        }
        
        public void hasPermission() {
            base.Channel.hasPermission();
        }
        
        public void hasPermissionAsync() {
            base.Channel.hasPermissionAsync();
        }
        
        public void connectAndMapSingleLoginNew() {
            base.Channel.connectAndMapSingleLoginNew();
        }
        
        public void connectAndMapSingleLoginNewAsync() {
            base.Channel.connectAndMapSingleLoginNewAsync();
        }
        
        public void connectAndSave() {
            base.Channel.connectAndSave();
        }
        
        public void connectAndSaveAsync() {
            base.Channel.connectAndSaveAsync();
        }
        
        public void connectAndSave1() {
            base.Channel.connectAndSave1();
        }
        
        public void connectAndSave1Async() {
            base.Channel.connectAndSave1Async();
        }
        
        public void connectNew() {
            base.Channel.connectNew();
        }
        
        public void connectNewAsync() {
            base.Channel.connectNewAsync();
        }
        
        public void connectNew1() {
            base.Channel.connectNew1();
        }
        
        public void connectNew1Async() {
            base.Channel.connectNew1Async();
        }
        
        public void connectNew2() {
            base.Channel.connectNew2();
        }
        
        public void connectNew2Async() {
            base.Channel.connectNew2Async();
        }
        
        public void connectNew3() {
            base.Channel.connectNew3();
        }
        
        public void connectNew3Async() {
            base.Channel.connectNew3Async();
        }
        
        public void connectNew4() {
            base.Channel.connectNew4();
        }
        
        public void connectNew4Async() {
            base.Channel.connectNew4Async();
        }
        
        public void connectNew5() {
            base.Channel.connectNew5();
        }
        
        public void connectNew5Async() {
            base.Channel.connectNew5Async();
        }
        
        public void connectNew6() {
            base.Channel.connectNew6();
        }
        
        public void connectNew6Async() {
            base.Channel.connectNew6Async();
        }
        
        public void connectNew7() {
            base.Channel.connectNew7();
        }
        
        public void connectNew7Async() {
            base.Channel.connectNew7Async();
        }
        
        public void connectNew8() {
            base.Channel.connectNew8();
        }
        
        public void connectNew8Async() {
            base.Channel.connectNew8Async();
        }
        
        public void connectNew9() {
            base.Channel.connectNew9();
        }
        
        public void connectNew9Async() {
            base.Channel.connectNew9Async();
        }
        
        public void connectAndSaveNew() {
            base.Channel.connectAndSaveNew();
        }
        
        public void connectAndSaveNewAsync() {
            base.Channel.connectAndSaveNewAsync();
        }
        
        public void connectAndSaveNew1() {
            base.Channel.connectAndSaveNew1();
        }
        
        public void connectAndSaveNew1Async() {
            base.Channel.connectAndSaveNew1Async();
        }
        
        public void connectAndSaveNew2() {
            base.Channel.connectAndSaveNew2();
        }
        
        public void connectAndSaveNew2Async() {
            base.Channel.connectAndSaveNew2Async();
        }
        
        public void changePassword() {
            base.Channel.changePassword();
        }
        
        public void changePasswordAsync() {
            base.Channel.changePasswordAsync();
        }
        
        public void changePassword1() {
            base.Channel.changePassword1();
        }
        
        public void changePassword1Async() {
            base.Channel.changePassword1Async();
        }
        
        public void changePassword2() {
            base.Channel.changePassword2();
        }
        
        public void changePassword2Async() {
            base.Channel.changePassword2Async();
        }
        
        public void isAccountActive() {
            base.Channel.isAccountActive();
        }
        
        public void isAccountActiveAsync() {
            base.Channel.isAccountActiveAsync();
        }
        
        public void isAccountActive1() {
            base.Channel.isAccountActive1();
        }
        
        public void isAccountActive1Async() {
            base.Channel.isAccountActive1Async();
        }
        
        public void getAccessRights() {
            base.Channel.getAccessRights();
        }
        
        public void getAccessRightsAsync() {
            base.Channel.getAccessRightsAsync();
        }
        
        public void generatePassword() {
            base.Channel.generatePassword();
        }
        
        public void generatePasswordAsync() {
            base.Channel.generatePasswordAsync();
        }
        
        public void isSessionValid() {
            base.Channel.isSessionValid();
        }
        
        public void isSessionValidAsync() {
            base.Channel.isSessionValidAsync();
        }
        
        public void auditGovtWarning() {
            base.Channel.auditGovtWarning();
        }
        
        public void auditGovtWarningAsync() {
            base.Channel.auditGovtWarningAsync();
        }
        
        public void headerLogin() {
            base.Channel.headerLogin();
        }
        
        public void headerLoginAsync() {
            base.Channel.headerLoginAsync();
        }
        
        public void connectPkiAndUserId() {
            base.Channel.connectPkiAndUserId();
        }
        
        public void connectPkiAndUserIdAsync() {
            base.Channel.connectPkiAndUserIdAsync();
        }
        
        public void proxyLoginAndUserID() {
            base.Channel.proxyLoginAndUserID();
        }
        
        public void proxyLoginAndUserIDAsync() {
            base.Channel.proxyLoginAndUserIDAsync();
        }
        
        public void unMapCert() {
            base.Channel.unMapCert();
        }
        
        public void unMapCertAsync() {
            base.Channel.unMapCertAsync();
        }
        
        public void unMapProxyId() {
            base.Channel.unMapProxyId();
        }
        
        public void unMapProxyIdAsync() {
            base.Channel.unMapProxyIdAsync();
        }
        
        public void getUserProfile() {
            base.Channel.getUserProfile();
        }
        
        public void getUserProfileAsync() {
            base.Channel.getUserProfileAsync();
        }
    }
}
